### PR TITLE
refactor online-status.php

### PR DESCRIPTION
**Pull request by bill-auger**
* factored data fetching into a function

### CODE REVIEW

**Comment by Wapaca** [comment]
It doesn't work anymore http://webdeveloper.fr.nf/auth/online-status.php :/ after the user being redirected i'm not loged and i changed the redirected url as you need at least http:// as prefix to be able to set it in the api on the app. $REDIRECT_URL  = 'http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];

**Comment by Wapaca** [comment]
I think the user you enter the redirect_url url manually as he may wants to redirect to another page than this one and it causes troubles when the user return from auth with an ?error inside the url, it keeps it in the auth link.

**Comment by Wapaca** [comment]
I found issues in your script.

First you must enter the url manually cause once you do checkCodes with your redirect url it put ?state and ?code inside so the request become invalid and second you can't exit the script without the channel name cause when the user come back from the auth url there is no more ?channel in the url and your exit block the auth part.

**Comment by bill-auger** [comment]
yes you are correct - i was thinking to try adding ?channel=$CHANNEL to the redirect url to see if maybe it preserves it - or else yea would need to load the sessinon first then do something like
```php
session_start();
$lctv_user =  htmlspecialchars($_GET['channel']) ||  $_SESSION['channel'] ;
```

**Comment by Wapaca** [comment]
Yes it's better to retrieve it from the session cause as you must authorize your redirect urls in the app settings it's impossible to authorize 1 url for each lctv channel.

**Comment by bill-auger** [comment]
ok so it should be then the other way round then?
```php
session_start();
$lctv_user =    $_SESSION['channel'] || htmlspecialchars($_GET['channel']) ;
```

**Comment by Wapaca** [comment]
I have made some modifications and now it's working perfectly.

Did this cause your line return a boolean in php 
$lctv_user =    (isset($_SESSION['channel']))
                  ? $_SESSION['channel']
                  : (isset($_GET['channel']))
                    ? htmlspecialchars($_GET['channel'])
                    : null ;

How can i do a commit to your pull request ? :D

**Comment by bill-auger** [comment]
ah yes and regarding the $REDIRECT_URL - i remember now i figured that need to be hard coded because you must enter a reditrect URL in the app configuration on the LCTV API website - so i assumed they must match - but i am not sure if this is true or not

**Comment by Wapaca** [comment]
Yes they must perfectly match

**Comment by bill-auger** [comment]
if you want to keep the changes that are in this PR then you just click the bug fat "Merge" button 

then goto you local terminal and type
```
git fetch --all
git merge origin master
```

**Comment by bill-auger** [comment]
ok so if the redirect URL must match the one on the API server then my original form was best (getting it from the local environment or user hard-coded)
```
$REDIRECT_URL  = getenv('LCTV_REDIRECT_URL');
```

should actually be constants but i could not remember how then

**Comment by bill-auger** [comment]
oh and i dont have a server setup on this box i was testing on a VPS - should i fire it back up ?

**Comment by Wapaca** [comment]
I'm using a digitalocean droplet to test ;)

**Comment by bill-auger** [comment]
was just saying im not setup to test anything on this arch box (like your boolen snippet above) 

this is turning into a chat go to your LCTV channel so i can see how are you making out

**Pull request merged**
